### ISSUE TITLE
Disabling all modules in the group ['realm_ad', 'realm'] due to a failure in one of them: Parameter 'computername_ prefix' is expected to have a non-empty value

### ISSUE THREAD

**Issue by RedChops** [theforeman/smart_proxy_realm_ad_plugin#15]
If I leave computername_prefix unset or commented out in realm_ad.yml, I get the error mentioned in the subject. No clue why, as that setting is not mentioned in the validators. What I ended up doing was modifying configuration_loader.rb with computername_prefix: '' then putting any value for that setting in realm_ad.yml and it seemed to work. This is obviously not a general case fix, but I personally have no use for the field.

I should mention that I'm currently using Foreman 1.18

**Comment by martencassel** [comment]
computername_prefix  is currently required. The solution is to comment this out. 
We will probably fix this later.

**Comment by martencassel** [comment]
can we close this issue ?

**Comment by RedChops** [comment]
I forgot this ticket was still opened, we haven't used this plugin in nearly 4 years.
