### ISSUE TITLE
Disabling all modules in the group ['realm']: following providers are not available ['realm_ad']

### ISSUE THREAD

**Issue by a118n** [theforeman/smart_proxy_realm_ad_plugin#25]
Installed the plugin via `sudo dnf install -y rubygem-smart_proxy_realm_ad_plugin`
Then I'm trying to enable the feature as follows:
```
sudo foreman-installer --scenario katello \
--foreman-proxy-realm true \
--foreman-proxy-realm-provider ad \
--foreman-proxy-realm-keytab /usr/share/foreman-proxy/svc-foreman.keytab \
--foreman-proxy-realm-principal svc-foreman@MYDOMAIN.NET
```

But I get the error:
Disabling all modules in the group ['realm']: following providers are not available ['realm_ad']

Also tried installing the gem as `sudo gem install smart_proxy_realm_ad_plugin` but I'm getting the same result.

OS: Rocky Linux 8.6
Foreman 3.3
Katello 4.5

Am I missing something?

**Comment by martencassel** [comment]
Hi i am afk currently but ill check it out later :)
